### PR TITLE
Skip whole genome records

### PR DESCRIPTION
**Pull request by antunderwood**
In order to prepare the NCBI acquired gene database, the records that are whole genome as determined by a prefix of 'AP' should be skipped

### CODE REVIEW

**Comment by puethe** [comment]
Hi Anthony, happy to merge this in, just wondering if there were any tests that would profit from adapting? If not happy to go ahead.

**Comment by jacquikeane** [comment]
Any chance we can get this merged (even without tests!) and a new release to allow people to use this with the ncbi acquired gene database?

**Comment by puethe** [comment]
Hi @jacquikeane , I am no longer working at the Sanger and do not have permissions on the repo anymore. You'll have to contact the team. Cheers Christoph

**Comment by martinghunt** [comment]
Am merging. @jacquikeane new release is another thing though - I've no idea what the release process is for this repo now! I'm going to look at updating to use github actions

**Pull request merged**
