### PR TITLE
fix card db path

### PR DESCRIPTION
**Pull request by eppinglen**

### CODE REVIEW

**Comment by martinghunt** [comment]
This will break on versions <= 1.2.1 of the download because they are bz2 not gz. I think changing the end of the regex to `\.(gz|bz2)` would work?

The next question is whether the extension in the filename is used in line 93 or not. If the correct extension is needed, then it will need to be captured by the regex and then used in line 88 so that the right extension is used.

**Comment by eppinglen** [comment]
Yes, the regex solved that issue for all card versions. I did not know that all card versions  have to be supported. 

The tarfile module in python just checks if the extension name is valid. For unpacking it doesn't matter if it is bz2, gz or just tar. So there won't be a problem in line 93 and 88.

**Comment by martinghunt** [comment]
Awesome! Thanks for that!

**Comment by ssjunnebo** [comment]
Is this ok to merge?

**Comment by martinghunt** [comment]
All fine with me, so long as older version downloads still work

**Pull request merged**
