### PR TITLE
Megares fixes v3

### PR DESCRIPTION
**Pull request by aastha-batta**
I have added a few fixes for megares v3.0 
Kindly look into it.

### CODE REVIEW

**Comment by aastha-batta** [comment]
Added relevant changes to samtools_variants.py for issue #327 
Kindly look into it.

**Comment by martinghunt** [comment]
One of the megares tests is broken by these changes. Here's the relevant part of the github actions log:

```2023-05-24T08:14:36.3352131Z FAIL: test_zips_from_index_page_string (ariba.tests.megares_data_finder_test.TestMegaresDataFinder)
2023-05-24T08:14:36.3352482Z test _zips_from_index_page_string
2023-05-24T08:14:36.3352879Z ----------------------------------------------------------------------
2023-05-24T08:14:36.3353189Z Traceback (most recent call last):
2023-05-24T08:14:36.3353535Z   File "/ariba/ariba/tests/megares_data_finder_test.py", line 26, in test_zips_from_index_page_string
2023-05-24T08:14:36.3353886Z     self.assertEqual(expected, got)
2023-05-24T08:14:36.3354467Z AssertionError: {'1.00': 'megares_v1.00.zip', '1.01': 'megares_v1.01.zip'} != {}
2023-05-24T08:14:36.3354894Z - {'1.00': 'megares_v1.00.zip', '1.01': 'megares_v1.01.zip'}
2023-05-24T08:14:36.3355120Z + {}
```

For the bcftools/mpileup issue, I just commented on it:
https://github.com/sanger-pathogens/ariba/issues/327#issuecomment-1564086795

**Comment by aastha-batta** [comment]
Hi, the test broke as i added the newest version of megares which is version3 to the code. I will update the test file too in order to ensure efficient testing. Thank you @martinghunt

**Comment by martinghunt** [comment]
Thank you @aastha-batta . Could you also remove the mpileup changes and keep this PR to just fix megares? I'll sort out mpileup in a separate PR, once I've figured out how to do it.

**Comment by aastha-batta** [comment]
Ok @martinghunt will do the needful.

**Pull request closed without merging**
