### PR TITLE
Added getref feature for NCBI's Bacterial Antimicrobial Resistance Reference Gene Database

### PR DESCRIPTION
**Pull request by schultzm**
Hi `ARIBA` team, 

With this pull request, the user can now do `ariba getref ncbi ncbi.getref` to download the Bacterial Antimicrobial Resistance Reference Gene Database of over 4000 curated AMR genes.   Unitests have been put in place, which can be run for the new feature doing `python3 ariba/ariba/tests/ncbi_getter_test.py `.  I have updated the version number to `2.14.0`.

Cheers, 

Mark

### CODE REVIEW

**Comment by kpepper** [comment]
Hi  **@schultzm**, thanks for the PR. Should be able to merge early next week.

**Comment by schultzm** [comment]
@kpepper changes have been made as requested and Travis build has now passed as predicted.  Thanks.

**Comment by schultzm** [comment]
@kpepper changes made as requested. Travis build now passes.  Thanks.

**Comment by kpepper** [comment]
Hi **@schultzm**,
Was there any particular reason for removing the following line from the MANIFEST.in:
recursive-include third_party *.h
I think it's causing the PyPi/Bioconda builds to fall over as the compiler can't find "bseq.h" - the PyPi tar is missing the .h files.
Thanks.

**Pull request merged**
